/*
 * JSON Placeholder
 * Fake Online REST API for Testing and Prototyping
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * UserCompany
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-03T22:13:09.964+13:00")
public class UserCompany {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("catchPhrase")
  private String catchPhrase = null;

  @JsonProperty("bs")
  private String bs = null;

  public UserCompany name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UserCompany catchPhrase(String catchPhrase) {
    this.catchPhrase = catchPhrase;
    return this;
  }

   /**
   * Get catchPhrase
   * @return catchPhrase
  **/
  @ApiModelProperty(value = "")
  public String getCatchPhrase() {
    return catchPhrase;
  }

  public void setCatchPhrase(String catchPhrase) {
    this.catchPhrase = catchPhrase;
  }

  public UserCompany bs(String bs) {
    this.bs = bs;
    return this;
  }

   /**
   * Get bs
   * @return bs
  **/
  @ApiModelProperty(value = "")
  public String getBs() {
    return bs;
  }

  public void setBs(String bs) {
    this.bs = bs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserCompany userCompany = (UserCompany) o;
    return Objects.equals(this.name, userCompany.name) &&
        Objects.equals(this.catchPhrase, userCompany.catchPhrase) &&
        Objects.equals(this.bs, userCompany.bs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, catchPhrase, bs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserCompany {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    catchPhrase: ").append(toIndentedString(catchPhrase)).append("\n");
    sb.append("    bs: ").append(toIndentedString(bs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

