/*
 * JSON Placeholder
 * Fake Online REST API for Testing and Prototyping
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.client.api;

import com.example.client.model.NotFoundError;
import com.example.client.model.Photo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PhotosApi
 */
@Ignore
public class PhotosApiTest {

    private final PhotosApi api = new PhotosApi();

    
    /**
     * Get specific photo
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPhotoTest() {
        Integer id = null;
        Photo response = api.getPhoto(id);

        // TODO: test validations
    }
    
    /**
     * Get all available photos
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPhotosTest() {
        Integer id = null;
        Integer albumId = null;
        List<Photo> response = api.getPhotos(id, albumId);

        // TODO: test validations
    }
    
}
