/*
 * JSON Placeholder
 * Fake Online REST API for Testing and Prototyping
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.client.api;

import com.example.client.model.Comment;
import com.example.client.model.NotFoundError;
import com.example.client.model.Post;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PostsApi
 */
@Ignore
public class PostsApiTest {

    private final PostsApi api = new PostsApi();

    
    /**
     * Get all available posts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPostsTest() {
        Integer id = null;
        Integer userId = null;
        List<Post> response = api.getPosts(id, userId);

        // TODO: test validations
    }
    
    /**
     * Get comments for a specific post
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postsIdCommentsGetTest() {
        Integer id = null;
        List<Comment> response = api.postsIdCommentsGet(id);

        // TODO: test validations
    }
    
    /**
     * Get specific post
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postsIdGetTest() {
        Integer id = null;
        Post response = api.postsIdGet(id);

        // TODO: test validations
    }
    
}
